volumes:
  dareg-postgres15:

services:
  postgres:
    image: postgres:15.4
    volumes:
      - dareg-postgres15:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass123worD
      POSTGRES_DB: dareg

  dareg:
    # image: registry.gitlab.ics.muni.cz:443/ceitec-cf-biodata/dareg:devel
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COMMIT_DATE: "2020-01-01"
        COMMIT_HASH: "not_set"
    # depends_on:
    #   - postgres
    ports:
      - 8083:8080
    develop:
      watch:
        - path: ./dareg
          action: sync
          target: /srv/dareg
          x-initialSync: true
          ignore:
            - .git
            - .gitignore
            - .gitlab
            - .gitlab-ci.yml
            - .dockerignore
            - backend
            - .venv
            - .vscode
            - __pycache__
    env_file:
      - .env
    environment:
      # In production mode requests are served by Gunicorn webserver
      PRODUCTION: false
      DJANGO_DEBUG: True
      # List of allowed hosts separated by spaces (e.g.: "localhost domain.xyz 10.0.0.1")
      # If set to "*" all hosts are allowed
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_ALLOWED_ORIGINS: "http://localhost:8083 http://localhost http://localhost:5000"
      # DB_HOST: postgres
      # DB_USER: postgres
      # DB_PASSWORD: pass123worD
      # DB_NAME: dareg
      # DB_PORT: 5432
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8084:8080
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
