# Generated by Django 4.2.16 on 2024-10-07 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid

def populate_uuid_ids(apps, schema_editor):
    UserProfile = apps.get_model('api', 'UserProfile')
    for profile in UserProfile.objects.all():
        profile.uuid_id = uuid.uuid4()
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_dataset_onedata_dataset_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=False, serialize=False),
        ),
        migrations.RunPython(populate_uuid_ids),
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False, serialize=False),
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='uuid_id',
            new_name='id',
        ),
    ]