# Generated by Django 4.2.24 on 2025-10-05 14:46

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_dataset_onedata_space_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='onedata_space_id',
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('onedata_workflow_id', models.CharField(max_length=200, verbose_name='Onedata Workflow ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('revision', models.DecimalField(decimal_places=0, default=1, max_digits=10, verbose_name='Revision')),
                ('input_params', models.JSONField(blank=True, default=dict, verbose_name='JSON')),
                ('workflow_type', models.CharField(choices=[('WriteData', 'WRITE_DATA'), ('Readonly', 'READONLY'), ('In-placeChange', 'IN_PLACE_CHANGE'), ('Export', 'EXPORT')], default=api.models.WorkflowType['READONLY'], max_length=20, verbose_name='Workflow Type')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'workflowtemplate',
                'verbose_name_plural': 'workflowtemplates',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('root_resource_id', models.UUIDField(blank=True, help_text='ID of the related object (Project, Dataset, or Experiment)', null=True)),
                ('output_resource_id', models.UUIDField(blank=True, help_text='ID of the related object (Dataset or Experiment)', null=True)),
                ('onedata_workflow_execution_id', models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Onedata Workflow Execution ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('status', models.CharField(choices=[('new', 'NEW'), ('assigning', 'ASSIGNING'), ('assigned', 'ASSIGNED'), ('running', 'RUNNING'), ('success', 'SUCCESS'), ('failure', 'FAILURE'), ('submissionError', 'SUBMISSION_ERROR'), ('pollingError', 'POLLING_ERROR')], default=api.models.JobStatus['NEW'], editable=False, max_length=20)),
                ('app_config', models.JSONField(default=dict, verbose_name='App config json')),
                ('start_time', models.DateTimeField(blank=True, editable=False, max_length=200, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, editable=False, max_length=200, null=True, verbose_name='End Time')),
                ('log_level', models.CharField(blank=True, choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warning', 'WARNING')], default=api.models.JobLogLevel['INFO'], max_length=20)),
                ('job_submission_counter', models.IntegerField(default=0, help_text='Number of times job submission has been attempted', verbose_name='Job Submission Counter')),
                ('job_polling_counter', models.IntegerField(default=0, help_text='Number of times job status polling has failed', verbose_name='Job Polling Counter')),
                ('claimed', models.BooleanField(default=False, help_text='Whether this job is currently claimed by a worker for processing', verbose_name='Job Claimed')),
                ('claimed_at', models.DateTimeField(blank=True, help_text='Timestamp when the job was claimed', null=True, verbose_name='Claimed At')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('output_resource_content_type', models.ForeignKey(blank=True, help_text='Content type of the related object (Dataset or Experiment)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_output_resource', to='contenttypes.contenttype')),
                ('root_resource_content_type', models.ForeignKey(blank=True, help_text='Content type of the related object (Project, Dataset, or Experiment)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_root_resource', to='contenttypes.contenttype')),
                ('workflow_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.workflowtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='workflow_templates',
            field=models.ManyToManyField(blank=True, related_name='supported_projects', to='api.workflowtemplate'),
        ),
    ]
