# Generated by Django 4.2.23 on 2025-07-13 14:25

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0016_dataset_onedata_space_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_id', models.CharField(max_length=200, unique=True, verbose_name='Workflow ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('revision', models.DecimalField(decimal_places=0, default=1, max_digits=10, verbose_name='Revision')),
                ('input_params', models.JSONField(blank=True, default=dict, verbose_name='JSON')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_id', models.CharField(max_length=200, unique=True, verbose_name='Workflow ID')),
                ('object_id', models.UUIDField(editable=False, help_text='Object id', null=True)),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('status', models.CharField(choices=[('new', 'NEW'), ('prepared', 'PREPARED'), ('running', 'RUNNING'), ('synchronizing', 'SYNCHRONIZING'), ('success', 'SUCCESS'), ('failure', 'FAILURE'), ('discarded', 'DISCARDED')], default=api.models.JobStatus['NEW'], max_length=20)),
                ('input_params', models.JSONField(blank=True, default=dict, verbose_name='JSON')),
                ('start_time', models.DateTimeField(blank=True, max_length=200, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, max_length=200, null=True, verbose_name='End Time')),
                ('log_level', models.CharField(choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warning', 'WARNING')], default=api.models.JobLogLevel['INFO'], max_length=20)),
                ('content_type', models.ForeignKey(help_text='Content type of the model', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('workflow_temaplate_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.workflowtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
