# Generated by Django 4.2.24 on 2025-09-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_workflow_and_job_model'),
        ('api', '0017_enable_pg_trm'),
    ]

    operations = [
    ]
