# Generated by Django 4.2.24 on 2025-09-14 14:55

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0018_merge_20250914_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowtemplate',
            options={'verbose_name': 'workflowtemplate', 'verbose_name_plural': 'workflowtemplates'},
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='onedata_space_id',
        ),
        migrations.RemoveField(
            model_name='workflowtemplate',
            name='project_id',
        ),
        migrations.AddField(
            model_name='job',
            name='workflow_execution_id',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Workflow Execution ID'),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='projects',
            field=models.ManyToManyField(to='api.project'),
        ),
        migrations.AlterField(
            model_name='job',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Content type of the related object (Project, Dataset, or Experiment)', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_time',
            field=models.DateTimeField(blank=True, editable=False, max_length=200, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='job',
            name='input_params',
            field=models.JSONField(default=dict, verbose_name='JSON'),
        ),
        migrations.AlterField(
            model_name='job',
            name='log_level',
            field=models.CharField(blank=True, choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warning', 'WARNING')], default=api.models.JobLogLevel['INFO'], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='object_id',
            field=models.UUIDField(blank=True, help_text='ID of the related object (Project, Dataset, or Experiment)', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_time',
            field=models.DateTimeField(blank=True, editable=False, max_length=200, null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('running', 'RUNNING'), ('scheduling', 'SCHEDULING'), ('success', 'SUCCESS'), ('failure', 'FAILURE')], default=api.models.JobStatus['NEW'], editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='workflow_id',
            field=models.CharField(max_length=200, verbose_name='Workflow ID'),
        ),
    ]
