# Generated by Django 4.2.24 on 2025-09-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_dataset_onedata_space_id_workflowtemplate_job_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='workflow_temaplate_id',
            new_name='workflow_template_id',
        ),
    ]