# Generated by Django 4.2.24 on 2025-09-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_change_workflowtemplate_project_to_m2m'),
    ]

    operations = [
    ]
