# Generated by Django 4.2.24 on 2025-09-15 05:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_fix_workflowtemplate_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='workflow_type',
            field=models.CharField(choices=[('WriteData', 'WRITE_DATA'), ('Readonly', 'READONLY'), ('In-placeChange', 'IN_PLACE_CHANGE'), ('Export', 'EXPORT')], default=api.models.WorkflowType['READONLY'], max_length=20, verbose_name='Workflow Type'),
        ),
    ]
