# Generated by Django 4.2.24 on 2025-09-28 13:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_submission_counter',
            field=models.IntegerField(default=0, help_text='Number of times job submission has been attempted', verbose_name='Job Submission Counter'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('assigning', 'ASSIGNING'), ('assigned', 'ASSIGNED'), ('running', 'RUNNING'), ('success', 'SUCCESS'), ('failure', 'FAILURE'), ('unknownError', 'UNKNOWN_ERROR')], default=api.models.JobStatus['NEW'], editable=False, max_length=20),
        ),
    ]