# Generated by Django 4.2.24 on 2025-09-28 14:01

from django.db import migrations


def migrate_unknown_error_statuses(apps, schema_editor):
    """
    Migrate jobs with old 'unknownError' status to new specific error statuses.
    Since we can't determine the exact cause, we'll use submission counters as a heuristic:
    - If job_submission_counter > 0, it was likely a submission error
    - Otherwise, assume it was a polling error
    """
    Job = apps.get_model('api', 'Job')

    unknown_jobs = Job.objects.filter(status='unknownError')
    print(f"Migrating {unknown_jobs.count()} jobs from 'unknownError' status...")

    for job in unknown_jobs:
        if job.job_submission_counter > 0:
            # Likely a submission error
            job.status = 'submissionError'
            print(f"Job {job.id}: unknownError -> submissionError (submission_counter={job.job_submission_counter})")
        else:
            # Assume it was a polling error
            job.status = 'pollingError'
            print(f"Job {job.id}: unknownError -> pollingError (submission_counter={job.job_submission_counter})")

        job.save(update_fields=['status'])

    print(f"Migration complete: {unknown_jobs.count()} jobs updated")


def reverse_migrate_unknown_error_statuses(apps, schema_editor):
    """
    Reverse migration - convert specific errors back to unknownError
    """
    Job = apps.get_model('api', 'Job')

    submission_errors = Job.objects.filter(status='submissionError')
    polling_errors = Job.objects.filter(status='pollingError')

    for job in submission_errors:
        job.status = 'unknownError'
        job.save(update_fields=['status'])

    for job in polling_errors:
        job.status = 'unknownError'
        job.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_job_status'),
    ]

    operations = [
        migrations.RunPython(
            migrate_unknown_error_statuses,
            reverse_migrate_unknown_error_statuses
        ),
    ]